version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3
      - run:
          name: run tests
          command: |
            bundle exec rspec
